## Imports

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn import metrics as mt

## Load Dataset

In [2]:
df = pd.read_csv('/home/lucas/projetos/exercicios_ds_ml/dataset/train.csv')

## Data Preparation

In [3]:
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

In [4]:
df.columns

Index(['id_cliente', 'idade', 'saldo_atual', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros',
       'investe_exterior', 'pessoa_polit_exp', 'limite_adicional'],
      dtype='str')

In [5]:
#seleciono as variáveis que acho que está relacionada a variável resposta, que é saldo_atual
features = ['idade', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']

#variável resposta, o que quero estudar
label = ['saldo_atual']

In [6]:
#crio um dataset para x_train e y_train com todas linhas e suas colunas respectivas
x_train = df.loc[:, features]
y_train = df.loc[:, label]

## Model Training

In [7]:
#model definition
lr_model = LinearRegression()

#model fit (ajuste, parametros)
lr_model.fit(x_train, y_train)

LinearRegression()

In [8]:
#de curiosidade, olhando o coef de cada features, 
lr_model.coef_

array([[ 3.96706202e-04, -4.00595601e-02,  2.77622532e-06,
        -1.04318668e-03,  9.80890872e+00, -1.22353405e-02,
        -6.33015538e-03, -3.57808095e-03, -2.15858165e+00,
         3.77570060e-04,  6.79176336e-03,  3.48471845e-03]])

In [9]:
#previsão
y_pred = lr_model.predict(x_train)
y_pred

array([[346.66954862],
       [367.84027655],
       [431.46897895],
       ...,
       [412.25174802],
       [400.68529863],
       [455.26482252]], shape=(9500, 1))

In [10]:
#quero criar uma dataframe com os valores definidos e os previstos
#crio um df1 com id cliente e saldo atual(valor pré definido)
#depois adiciono uma coluna 'predict' para receber os valores previstos
df1 = df.loc[:, ['id_cliente', 'saldo_atual']]
df1['predict'] = y_pred
df1.head()

   id_cliente  saldo_atual     predict
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

## Performance

In [11]:
#calcular agora o R2 para ver a performance desse predict
#resposta: consigo explicar 16,9% do fenômeno observado a partir 
#das features que tenho em mãos. 
#resultado baixo para negócios.

mt.r2_score(y_train, y_pred)

0.16917364489050002

### Utilizando a outra métrica, o MSE

In [12]:
## 4.1 R squared
r2_squared = np.round(100*mt.r2_score(y_train, y_pred), 2) 
print('R2 square: {}%'.format(r2_squared)) 

## 4.2 MSE
mse = np.round( mt.mean_squared_error(y_train, y_pred), 2) 
print('A cada previsão, o erro médio é de: U${}'.format(mse))


# 5.0 Conclusão
print('{}% da variação da variável alvo y é reduzida, levando em consideração o preditor'.format(r2_squared))
print('{}% da variação da variável alvo y é “explicada pela variação do preditor x'.format(r2_squared))

R2 square: 16.92%
A cada previsão, o erro médio é de: U$39370.27
16.92% da variação da variável alvo y é reduzida, levando em consideração o preditor
16.92% da variação da variável alvo y é “explicada pela variação do preditor x

### Utilizando a outra métrica, o RMSE

In [13]:
## 4.3 RMSE
rmse = np.sqrt(mse)
print('A cada previsão, o erro médio é de: U${}'.format(rmse))

A cada previsão, o erro médio é de: U$198.41942949217446

# Testando Métricas com Novos Outliers

### Estrutura da Ideia

1. criar uma cópia do dataframe x_train;
2. selecionar porcentagens (0%, 2%, 5%, 10%, 20% e 30%) das linhas a serem modificadas para outliers. Ou seja, terá 6 resultados diferentes, com níveis de outliers cada vez maiores;
3. Alterar algumas features dessas linhas para virar outliers;
4. treinar um novo modelo para cada variação de linhas modificadas;
5. prever o 'saldo_atual' que é o predict, para cada variação de linhas modificadas;
6. calcular o R², MSE e RMSE para cada variação de linhas modificadas;
7. Guardar os resultados em uma tabela;
8. Comparar e analisar os resultados entre as alterações.

### 1) criando variável que guarda porcentagens e features/colunas alteradas

In [14]:
#proporções de outliers que serão testadas
proporcoes_outliers = [0, 0.02, 0.05, 0.10, 0.20, 0.30]

#colunas que sofrerão alterações, virando outliers
colunas_outliers = [
    'divida_atual',
    'renda_anual',
    'valor_em_investimentos'
]

### 2) criando uma ordem aleatória das linhas a serem alteradas

In [15]:
#criando uma varíavel para guardar a aleatoriedade usando biblioteca Numpy e a função armazenada
#dentro dela, chamada random.default_rng que é considerado uma função de fábrica, 
#que serve para criar um gerador de números aleatórios (um objeto da classe Generator).
#42 é um número aleatório que vai padronizar como as linhas serão sortidas

#cria uma ferramenta do NumPy capaz de fazer sorteios, embaralhar e gerar números aleatórios.
random_number_generator = np.random.default_rng(42)

#agora utiliza a ferramenta criada acima e pega os indices de x_train e 
#coloca de fato em ordem aleatória e embaralhada
indices_aleatorios = random_number_generator.permutation(x_train.index)

### 3) treinando os modelos

In [ ]:
#crio uma variável chamada resultado para guardar os resultados
resultados = []

#faço um looping for agora para treinar todas variaçoes dos modelos
#para cada numero de % faça as seguintes operações
for i in proporcoes_outliers:

    #cria uma copia para preservar o x_train original
    x_train_modificado = x_train.copy()

    #calcula quantas linhas serão alteradas. i é a lista de proporções de outliers
    #int(passa a resposta inteira) e 
    #len(pega o tamanho total de linhas). Nesse caso retorna 9500 linhas
    #do total da amostra, quantas delas virarão outliers. Ex: 9500 * 0.05 (i [2])
    #ex: quantidade de linhas que serão modificadas = 475 (quantidade_outliers)
    quantidade_outliers = int(
        len(x_train_modificado) * i
    )

    #seleciona os indices que serão modificados
    #do total dessas amostragem, vai pegar do primeiro até o ultimo dela
    #exemplo, numero de 9500, a quantidade de outliers foi de 5% (i = 0.05)
    #então vai pegar as posições de 0-474 (475 primeiros numeros com index aleatorios)
    indices_outliers = indices_aleatorios[:quantidade_outliers]

    #multiplica por 10 os valores das colunas selecionadas
    #selecionou as linhas e as colunas
    #*= multiplica todos os valores por 10 e guarda no mesmo lugar aqui
    x_train_modificado.loc[indices_outliers, colunas_outliers]*=10

    #define o modelo usado
    modelo_outliers = LinearRegression()

    #treina o modelo com os dados modificados
    modelo_outliers.fit(
        x_train_modificado,
        y_train
    )

    #faz as previsões
    y_pred_outliers = modelo_outliers.predict(x_train_modificado)

    #calcula as metricas
    r2_outliers = mt.r2_score(
        y_train,
        y_pred_outliers
    )

    mse_outliers = mt.mean_squared_error(
        y_train,
        y_pred_outliers
    )

    rmse_outliers = np.sqrt(mse_outliers)

    #guarda o rsultado desta repetição
    resultados.append({
        'outliers_percentual': i*100,
        'quantidade_outliers': quantidade_outliers,
        'r2_outliers': r2_outliers*100,
        'mse_outliers': mse_outliers,
        'rmse_outliers': rmse_outliers
    })

### 4) Criando a Tabela e arredondando os resultados

In [31]:
df_resultados_outliers = pd.DataFrame(resultados)

df_resultados_outliers = df_resultados_outliers.round({
    'outliers_percentual': 0,
    'r2_outliers': 2,
    'mse_outliers': 2,
    'rmse_outliers': 2
})

df_resultados_outliers

,outliers_percentual,quantidade_outliers,r2_outliers,mse_outliers,rmse_outliers
0,0.0,0,16.92,39370.27,198.42
1,2.0,190,14.39,40569.39,201.42
2,5.0,475,14.24,40640.14,201.59
3,10.0,950,8.51,43356.42,208.22
4,20.0,1900,8.72,43257.04,207.98
5,30.0,2850,8.75,43240.34,207.94