# Import Bibliotecas

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Load Dataset

In [2]:
df = pd.read_csv('/home/lucas/projetos/exercicios_ds_ml/dataset/train.csv')

# Data Preparation

In [3]:
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

In [4]:
df.columns

Index(['id_cliente', 'idade', 'saldo_atual', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros',
       'investe_exterior', 'pessoa_polit_exp', 'limite_adicional'],
      dtype='str')

In [5]:
#seleciono as variáveis que acho que está relacionada a variável resposta, que é saldo_atual
features = ['idade', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']

#variável resposta, o que quero estudar
label = ['saldo_atual']

In [6]:
#crio x_train e y_train com todas linhas e suas colunas respectivas
x_train = df.loc[:, features]
y_train = df.loc[:, label]

# Model Training

In [7]:
#model definition
lr_model = LinearRegression()

#model fit (ajuste, treinamento)
lr_model.fit(x_train, y_train)

#previsão
y_pred = lr_model.predict(x_train)

In [8]:
#criei uma nova tabela, chamada df1, com todas linhas relacionadas a coluna id cliente e saldo atual(y)
df1 = df.loc[:, ['id_cliente', 'saldo_atual']]

#criei uma nova coluna, de predição, que produzimos os dados dela na previsão, y_pred
df1['predicted'] = y_pred

df1.head()

   id_cliente  saldo_atual   predicted
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

In [ ]:
#testando manualmente para várias features
#formula regressão linear com uma unica feature: y = a (intercepet) + bx
#formula regressão linear com várias features: y = a + b1x1 + b2x2 + b3x3 + b4x4 + ... b12x12)
#os "x" são as colunas/features (tem doze colunas) e os "b" são os coeficientes aprendidos p/ modelo
#depois que o modelo aprendeu a estrutura (lr_model.fit(x_xtrain, y_train)),
#ele acha "b" (lr_model.coef_) para cada feature e "a" (lr_model.intercept_).
#a formula abaixo faz então: pega todas features da linha 0, extrai o valores(values) e multiplica 
#pelos respectivos coeficientes, gerando multiplicação de matriz,
#e soma tudo. Depois disso soma com o intercept (a), achando o y, que é a previsão
y = lr_model.intercept_ + (np.sum(x_train.loc[0, :].values * lr_model.coef_))
y

array([346.66954862])

In [17]:
#testando manualmente com for
#para cada linha do tramanho de x_train, ou seja "varre" todas linhas
for i in range(len(x_train)):
    #colo o i no .loc, que vai determinar as linhas "varridas"
    print(lr_model.intercept_ + (np.sum(x_train.loc[i, :].values * lr_model.coef_)))

    #parar quando atingir a quarta linha, pois é só exemplo
    if i == 4:
        break

[346.66954862]
[367.84027655]
[431.46897895]
[445.50646329]
[378.27116865]